# This is the work of AR

import random
Elements = [
    {
        "Element_Name": "Hydrogen",
        "Element_Symbol": "H",
        "Atomic_Number": 1,
        "Atomic_Mass": 1.008,
        "Element_Group": 1,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 1,
        "Proton_Number": 1,
        "Electron_Number": 1,
        "Neutron_Number": 0
    },
    {
        "Element_Name": "Helium",
        "Element_Symbol": "He",
        "Atomic_Number": 2,
        "Atomic_Mass": 4.0026,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 2,
        "Electron_Number": 2,
        "Neutron_Number": 2
    },
    {
        "Element_Name": "Lithium",
        "Element_Symbol": "Li",
        "Atomic_Number": 3,
        "Atomic_Mass": 6.94,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 3,
        "Electron_Number": 3,
        "Neutron_Number": 4
    },
    {
        "Element_Name": "Beryllium",
        "Element_Symbol": "Be",
        "Atomic_Number": 4,
        "Atomic_Mass": 9.0122,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 4,
        "Electron_Number": 4,
        "Neutron_Number": 5
    },
    {
        "Element_Name": "Boron",
        "Element_Symbol": "B",
        "Atomic_Number": 5,
        "Atomic_Mass": 10.81,
        "Element_Group": 13,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 3,
        "Proton_Number": 5,
        "Electron_Number": 5,
        "Neutron_Number": 6
    },
    {
        "Element_Name": "Carbon",
        "Element_Symbol": "C",
        "Atomic_Number": 6,
        "Atomic_Mass": 12.011,
        "Element_Group": 14,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 4,
        "Proton_Number": 6,
        "Electron_Number": 6,
        "Neutron_Number": 6
    },
    {
        "Element_Name": "Nitrogen",
        "Element_Symbol": "N",
        "Atomic_Number": 7,
        "Atomic_Mass": 14.007,
        "Element_Group": 15,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 5,
        "Proton_Number": 7,
        "Electron_Number": 7,
        "Neutron_Number": 7
    },
    {
        "Element_Name": "Oxygen",
        "Element_Symbol": "O",
        "Atomic_Number": 8,
        "Atomic_Mass": 15.999,
        "Element_Group": 16,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 6,
        "Proton_Number": 8,
        "Electron_Number": 8,
        "Neutron_Number": 8
    },
    {
        "Element_Name": "Fluorine",
        "Element_Symbol": "F",
        "Atomic_Number": 9,
        "Atomic_Mass": 18.998,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 9,
        "Electron_Number": 9,
        "Neutron_Number": 10
    },
    {
        "Element_Name": "Neon",
        "Element_Symbol": "Ne",
        "Atomic_Number": 10,
        "Atomic_Mass": 20.180,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 10,
        "Electron_Number": 10,
        "Neutron_Number": 10
    },
        {
        "Element_Name": "Sodium",
        "Element_Symbol": "Na",
        "Atomic_Number": 11,
        "Atomic_Mass": 22.990,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 11,
        "Electron_Number": 11,
        "Neutron_Number": 12
    },
    {
        "Element_Name": "Magnesium",
        "Element_Symbol": "Mg",
        "Atomic_Number": 12,
        "Atomic_Mass": 24.305,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 12,
        "Electron_Number": 12,
        "Neutron_Number": 12
    },
    {
        "Element_Name": "Aluminum",
        "Element_Symbol": "Al",
        "Atomic_Number": 13,
        "Atomic_Mass": 26.982,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 13,
        "Electron_Number": 13,
        "Neutron_Number": 14
    },
    {
        "Element_Name": "Silicon",
        "Element_Symbol": "Si",
        "Atomic_Number": 14,
        "Atomic_Mass": 28.085,
        "Element_Group": 14,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 4,
        "Proton_Number": 14,
        "Electron_Number": 14,
        "Neutron_Number": 14
    },
    {
        "Element_Name": "Phosphorus",
        "Element_Symbol": "P",
        "Atomic_Number": 15,
        "Atomic_Mass": 30.974,
        "Element_Group": 15,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 5,
        "Proton_Number": 15,
        "Electron_Number": 15,
        "Neutron_Number": 16
    },
    {
        "Element_Name": "Sulfur",
        "Element_Symbol": "S",
        "Atomic_Number": 16,
        "Atomic_Mass": 32.06,
        "Element_Group": 16,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 6,
        "Proton_Number": 16,
        "Electron_Number": 16,
        "Neutron_Number": 16
    },
    {
        "Element_Name": "Chlorine",
        "Element_Symbol": "Cl",
        "Atomic_Number": 17,
        "Atomic_Mass": 35.45,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 17,
        "Electron_Number": 17,
        "Neutron_Number": 18
    },
    {
        "Element_Name": "Argon",
        "Element_Symbol": "Ar",
        "Atomic_Number": 18,
        "Atomic_Mass": 39.948,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 18,
        "Electron_Number": 18,
        "Neutron_Number": 22
    },
    {
        "Element_Name": "Potassium",
        "Element_Symbol": "K",
        "Atomic_Number": 19,
        "Atomic_Mass": 39.098,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 19,
        "Electron_Number": 19,
        "Neutron_Number": 20
    },
    {
        "Element_Name": "Calcium",
        "Element_Symbol": "Ca",
        "Atomic_Number": 20,
        "Atomic_Mass": 40.078,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 20,
        "Electron_Number": 20,
        "Neutron_Number": 20
    },
    {
        "Element_Name": "Scandium",
        "Element_Symbol": "Sc",
        "Atomic_Number": 21,
        "Atomic_Mass": 44.956,
        "Element_Group": 3,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 21,
        "Electron_Number": 21,
        "Neutron_Number": 24
    },
    {
        "Element_Name": "Titanium",
        "Element_Symbol": "Ti",
        "Atomic_Number": 22,
        "Atomic_Mass": 47.867,
        "Element_Group": 4,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 22,
        "Electron_Number": 22,
        "Neutron_Number": 26
    },
    {
        "Element_Name": "Vanadium",
        "Element_Symbol": "V",
        "Atomic_Number": 23,
        "Atomic_Mass": 50.942,
        "Element_Group": 5,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 5,
        "Proton_Number": 23,
        "Electron_Number": 23,
        "Neutron_Number": 28
    },
    {
        "Element_Name": "Chromium",
        "Element_Symbol": "Cr",
        "Atomic_Number": 24,
        "Atomic_Mass": 51.996,
        "Element_Group": 6,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 6,
        "Proton_Number": 24,
        "Electron_Number": 24,
        "Neutron_Number": 28
    },
    {
        "Element_Name": "Manganese",
        "Element_Symbol": "Mn",
        "Atomic_Number": 25,
        "Atomic_Mass": 54.938,
        "Element_Group": 7,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 7,
        "Proton_Number": 25,
        "Electron_Number": 25,
        "Neutron_Number": 30
    },
    {
        "Element_Name": "Iron",
        "Element_Symbol": "Fe",
        "Atomic_Number": 26,
        "Atomic_Mass": 55.845,
        "Element_Group": 8,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 26,
        "Electron_Number": 26,
        "Neutron_Number": 30
    },
    {
        "Element_Name": "Cobalt",
        "Element_Symbol": "Co",
        "Atomic_Number": 27,
        "Atomic_Mass": 58.933,
        "Element_Group": 9,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 27,
        "Electron_Number": 27,
        "Neutron_Number": 32
    },
    {
        "Element_Name": "Nickel",
        "Element_Symbol": "Ni",
        "Atomic_Number": 28,
        "Atomic_Mass": 58.693,
        "Element_Group": 10,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 28,
        "Electron_Number": 28,
        "Neutron_Number": 31
    },
    {
        "Element_Name": "Copper",
        "Element_Symbol": "Cu",
        "Atomic_Number": 29,
        "Atomic_Mass": 63.546,
        "Element_Group": 11,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 1,
        "Proton_Number": 29,
        "Electron_Number": 29,
        "Neutron_Number": 35
    },
    {
        "Element_Name": "Zinc",
        "Element_Symbol": "Zn",
        "Atomic_Number": 30,
        "Atomic_Mass": 65.38,
        "Element_Group": 12,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 30,
        "Electron_Number": 30,
        "Neutron_Number": 35
    },
    {
        "Element_Name": "Sodium",
        "Element_Symbol": "Na",
        "Atomic_Number": 11,
        "Atomic_Mass": 22.990,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 11,
        "Electron_Number": 11,
        "Neutron_Number": 12
    },
    {
        "Element_Name": "Magnesium",
        "Element_Symbol": "Mg",
        "Atomic_Number": 12,
        "Atomic_Mass": 24.305,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 12,
        "Electron_Number": 12,
        "Neutron_Number": 12
    },
    {
        "Element_Name": "Aluminum",
        "Element_Symbol": "Al",
        "Atomic_Number": 13,
        "Atomic_Mass": 26.982,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 13,
        "Electron_Number": 13,
        "Neutron_Number": 14
    },
    {
        "Element_Name": "Silicon",
        "Element_Symbol": "Si",
        "Atomic_Number": 14,
        "Atomic_Mass": 28.085,
        "Element_Group": 14,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 4,
        "Proton_Number": 14,
        "Electron_Number": 14,
        "Neutron_Number": 14
    },
    {
        "Element_Name": "Phosphorus",
        "Element_Symbol": "P",
        "Atomic_Number": 15,
        "Atomic_Mass": 30.974,
        "Element_Group": 15,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 5,
        "Proton_Number": 15,
        "Electron_Number": 15,
        "Neutron_Number": 16
    },
    {
        "Element_Name": "Sulfur",
        "Element_Symbol": "S",
        "Atomic_Number": 16,
        "Atomic_Mass": 32.06,
        "Element_Group": 16,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 6,
        "Proton_Number": 16,
        "Electron_Number": 16,
        "Neutron_Number": 16
    },
    {
        "Element_Name": "Chlorine",
        "Element_Symbol": "Cl",
        "Atomic_Number": 17,
        "Atomic_Mass": 35.45,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 17,
        "Electron_Number": 17,
        "Neutron_Number": 18
    },
    {
        "Element_Name": "Argon",
        "Element_Symbol": "Ar",
        "Atomic_Number": 18,
        "Atomic_Mass": 39.948,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 18,
        "Electron_Number": 18,
        "Neutron_Number": 22
    },
    {
        "Element_Name": "Potassium",
        "Element_Symbol": "K",
        "Atomic_Number": 19,
        "Atomic_Mass": 39.098,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 19,
        "Electron_Number": 19,
        "Neutron_Number": 20
    },
    {
        "Element_Name": "Calcium",
        "Element_Symbol": "Ca",
        "Atomic_Number": 20,
        "Atomic_Mass": 40.078,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 20,
        "Electron_Number": 20,
        "Neutron_Number": 20
    },
    {
        "Element_Name": "Scandium",
        "Element_Symbol": "Sc",
        "Atomic_Number": 21,
        "Atomic_Mass": 44.956,
        "Element_Group": 3,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 21,
        "Electron_Number": 21,
        "Neutron_Number": 24
    },
    {
        "Element_Name": "Titanium",
        "Element_Symbol": "Ti",
        "Atomic_Number": 22,
        "Atomic_Mass": 47.867,
        "Element_Group": 4,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 22,
        "Electron_Number": 22,
        "Neutron_Number": 26
    },
    {
        "Element_Name": "Vanadium",
        "Element_Symbol": "V",
        "Atomic_Number": 23,
        "Atomic_Mass": 50.942,
        "Element_Group": 5,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 5,
        "Proton_Number": 23,
        "Electron_Number": 23,
        "Neutron_Number": 28
    },
    {
        "Element_Name": "Chromium",
        "Element_Symbol": "Cr",
        "Atomic_Number": 24,
        "Atomic_Mass": 51.996,
        "Element_Group": 6,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 6,
        "Proton_Number": 24,
        "Electron_Number": 24,
        "Neutron_Number": 28
    },
    {
        "Element_Name": "Manganese",
        "Element_Symbol": "Mn",
        "Atomic_Number": 25,
        "Atomic_Mass": 54.938,
        "Element_Group": 7,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 7,
        "Proton_Number": 25,
        "Electron_Number": 25,
        "Neutron_Number": 30
    },
    {
        "Element_Name": "Iron",
        "Element_Symbol": "Fe",
        "Atomic_Number": 26,
        "Atomic_Mass": 55.845,
        "Element_Group": 8,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 26,
        "Electron_Number": 26,
        "Neutron_Number": 30
    },
    {
        "Element_Name": "Cobalt",
        "Element_Symbol": "Co",
        "Atomic_Number": 27,
        "Atomic_Mass": 58.933,
        "Element_Group": 9,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 27,
        "Electron_Number": 27,
        "Neutron_Number": 32
    },
    {
        "Element_Name": "Nickel",
        "Element_Symbol": "Ni",
        "Atomic_Number": 28,
        "Atomic_Mass": 58.693,
        "Element_Group": 10,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 28,
        "Electron_Number": 28,
        "Neutron_Number": 31
    },
    {
        "Element_Name": "Copper",
        "Element_Symbol": "Cu",
        "Atomic_Number": 29,
        "Atomic_Mass": 63.546,
        "Element_Group": 11,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 1,
        "Proton_Number": 29,
        "Electron_Number": 29,
        "Neutron_Number": 35
    },
    {
        "Element_Name": "Zinc",
        "Element_Symbol": "Zn",
        "Atomic_Number": 30,
        "Atomic_Mass": 65.38,
        "Element_Group": 12,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 30,
        "Electron_Number": 30,
        "Neutron_Number": 35
    },
    {
        "Element_Name": "Gallium",
        "Element_Symbol": "Ga",
        "Atomic_Number": 31,
        "Atomic_Mass": 69.723,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 31,
        "Electron_Number": 31,
        "Neutron_Number": 39
    },
    {
        "Element_Name": "Germanium",
        "Element_Symbol": "Ge",
        "Atomic_Number": 32,
        "Atomic_Mass": 72.630,
        "Element_Group": 14,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 4,
        "Proton_Number": 32,
        "Electron_Number": 32,
        "Neutron_Number": 41
    },
    {
        "Element_Name": "Arsenic",
        "Element_Symbol": "As",
        "Atomic_Number": 33,
        "Atomic_Mass": 74.922,
        "Element_Group": 15,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 5,
        "Proton_Number": 33,
        "Electron_Number": 33,
        "Neutron_Number": 42
    },
    {
        "Element_Name": "Selenium",
        "Element_Symbol": "Se",
        "Atomic_Number": 34,
        "Atomic_Mass": 78.971,
        "Element_Group": 16,
        "Element_Group_Type": "Nonmetal",
        "Element_Valence": 6,
        "Proton_Number": 34,
        "Electron_Number": 34,
        "Neutron_Number": 45
    },
    {
        "Element_Name": "Bromine",
        "Element_Symbol": "Br",
        "Atomic_Number": 35,
        "Atomic_Mass": 79.904,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 35,
        "Electron_Number": 35,
        "Neutron_Number": 45
    },
    {
        "Element_Name": "Krypton",
        "Element_Symbol": "Kr",
        "Atomic_Number": 36,
        "Atomic_Mass": 83.798,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 36,
        "Electron_Number": 36,
        "Neutron_Number": 48
    },
    {
        "Element_Name": "Rubidium",
        "Element_Symbol": "Rb",
        "Atomic_Number": 37,
        "Atomic_Mass": 85.468,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 37,
        "Electron_Number": 37,
        "Neutron_Number": 48
    },
    {
        "Element_Name": "Strontium",
        "Element_Symbol": "Sr",
        "Atomic_Number": 38,
        "Atomic_Mass": 87.62,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 38,
        "Electron_Number": 38,
        "Neutron_Number": 50
    },
    {
        "Element_Name": "Yttrium",
        "Element_Symbol": "Y",
        "Atomic_Number": 39,
        "Atomic_Mass": 88.906,
        "Element_Group": 3,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 39,
        "Electron_Number": 39,
        "Neutron_Number": 50
    },
    {
        "Element_Name": "Zirconium",
        "Element_Symbol": "Zr",
        "Atomic_Number": 40,
        "Atomic_Mass": 91.224,
        "Element_Group": 4,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 40,
        "Electron_Number": 40,
        "Neutron_Number": 51
    },
    {
        "Element_Name": "Niobium",
        "Element_Symbol": "Nb",
        "Atomic_Number": 41,
        "Atomic_Mass": 92.906,
        "Element_Group": 5,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 5,
        "Proton_Number": 41,
        "Electron_Number": 41,
        "Neutron_Number": 52
    },
    {
        "Element_Name": "Molybdenum",
        "Element_Symbol": "Mo",
        "Atomic_Number": 42,
        "Atomic_Mass": 95.95,
        "Element_Group": 6,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 6,
        "Proton_Number": 42,
        "Electron_Number": 42,
        "Neutron_Number": 54
    },
    {
        "Element_Name": "Technetium",
        "Element_Symbol": "Tc",
        "Atomic_Number": 43,
        "Atomic_Mass": 98,
        "Element_Group": 7,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 7,
        "Proton_Number": 43,
        "Electron_Number": 43,
        "Neutron_Number": 55
    },
    {
        "Element_Name": "Ruthenium",
        "Element_Symbol": "Ru",
        "Atomic_Number": 44,
        "Atomic_Mass": 101.07,
        "Element_Group": 8,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 44,
        "Electron_Number": 44,
        "Neutron_Number": 57
    },
    {
        "Element_Name": "Rhodium",
        "Element_Symbol": "Rh",
        "Atomic_Number": 45,
        "Atomic_Mass": 102.91,
        "Element_Group": 9,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 45,
        "Electron_Number": 45,
        "Neutron_Number": 58
    },
    {
        "Element_Name": "Palladium",
        "Element_Symbol": "Pd",
        "Atomic_Number": 46,
        "Atomic_Mass": 106.42,
        "Element_Group": 10,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 46,
        "Electron_Number": 46,
        "Neutron_Number": 60
    },
    {
        "Element_Name": "Silver",
        "Element_Symbol": "Ag",
        "Atomic_Number": 47,
        "Atomic_Mass": 107.87,
        "Element_Group": 11,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 1,
        "Proton_Number": 47,
        "Electron_Number": 47,
        "Neutron_Number": 61
    },
    {
        "Element_Name": "Cadmium",
        "Element_Symbol": "Cd",
        "Atomic_Number": 48,
        "Atomic_Mass": 112.41,
        "Element_Group": 12,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 48,
        "Electron_Number": 48,
        "Neutron_Number": 64
    },
    {
        "Element_Name": "Indium",
        "Element_Symbol": "In",
        "Atomic_Number": 49,
        "Atomic_Mass": 114.82,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 49,
        "Electron_Number": 49,
        "Neutron_Number": 66
    },
    {
        "Element_Name": "Tin",
        "Element_Symbol": "Sn",
        "Atomic_Number": 50,
        "Atomic_Mass": 118.71,
        "Element_Group": 14,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 50,
        "Electron_Number": 50,
        "Neutron_Number": 69
    },
    {
        "Element_Name": "Antimony",
        "Element_Symbol": "Sb",
        "Atomic_Number": 51,
        "Atomic_Mass": 121.76,
        "Element_Group": 15,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 5,
        "Proton_Number": 51,
        "Electron_Number": 51,
        "Neutron_Number": 71
    },
    {
        "Element_Name": "Tellurium",
        "Element_Symbol": "Te",
        "Atomic_Number": 52,
        "Atomic_Mass": 127.60,
        "Element_Group": 16,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 6,
        "Proton_Number": 52,
        "Electron_Number": 52,
        "Neutron_Number": 76
    },
    {
        "Element_Name": "Iodine",
        "Element_Symbol": "I",
        "Atomic_Number": 53,
        "Atomic_Mass": 126.90,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 53,
        "Electron_Number": 53,
        "Neutron_Number": 74
    },
    {
        "Element_Name": "Xenon",
        "Element_Symbol": "Xe",
        "Atomic_Number": 54,
        "Atomic_Mass": 131.29,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 54,
        "Electron_Number": 54,
        "Neutron_Number": 77
    },
    {
        "Element_Name": "Cesium",
        "Element_Symbol": "Cs",
        "Atomic_Number": 55,
        "Atomic_Mass": 132.91,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 55,
        "Electron_Number": 55,
        "Neutron_Number": 78
    },
    {
        "Element_Name": "Barium",
        "Element_Symbol": "Ba",
        "Atomic_Number": 56,
        "Atomic_Mass": 137.33,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 56,
        "Electron_Number": 56,
        "Neutron_Number": 81
    },
    {
        "Element_Name": "Lanthanum",
        "Element_Symbol": "La",
        "Atomic_Number": 57,
        "Atomic_Mass": 138.91,
        "Element_Group": 3,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 57,
        "Electron_Number": 57,
        "Neutron_Number": 82
    },
    {
        "Element_Name": "Cerium",
        "Element_Symbol": "Ce",
        "Atomic_Number": 58,
        "Atomic_Mass": 140.12,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 4,
        "Proton_Number": 58,
        "Electron_Number": 58,
        "Neutron_Number": 82
    },
    {
        "Element_Name": "Praseodymium",
        "Element_Symbol": "Pr",
        "Atomic_Number": 59,
        "Atomic_Mass": 140.91,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 59,
        "Electron_Number": 59,
        "Neutron_Number": 82
    },
    {
        "Element_Name": "Neodymium",
        "Element_Symbol": "Nd",
        "Atomic_Number": 60,
        "Atomic_Mass": 144.24,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 60,
        "Electron_Number": 60,
        "Neutron_Number": 84
    },
  {
        "Element_Name": "Promethium",
        "Element_Symbol": "Pm",
        "Atomic_Number": 61,
        "Atomic_Mass": 145,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 61,
        "Electron_Number": 61,
        "Neutron_Number": 84
    },
    {
        "Element_Name": "Samarium",
        "Element_Symbol": "Sm",
        "Atomic_Number": 62,
        "Atomic_Mass": 150.36,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 62,
        "Electron_Number": 62,
        "Neutron_Number": 88
    },
    {
        "Element_Name": "Europium",
        "Element_Symbol": "Eu",
        "Atomic_Number": 63,
        "Atomic_Mass": 151.96,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 63,
        "Electron_Number": 63,
        "Neutron_Number": 89
    },
    {
        "Element_Name": "Gadolinium",
        "Element_Symbol": "Gd",
        "Atomic_Number": 64,
        "Atomic_Mass": 157.25,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 64,
        "Electron_Number": 64,
        "Neutron_Number": 93
    },
    {
        "Element_Name": "Terbium",
        "Element_Symbol": "Tb",
        "Atomic_Number": 65,
        "Atomic_Mass": 158.93,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 65,
        "Electron_Number": 65,
        "Neutron_Number": 94
    },
    {
        "Element_Name": "Dysprosium",
        "Element_Symbol": "Dy",
        "Atomic_Number": 66,
        "Atomic_Mass": 162.50,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 66,
        "Electron_Number": 66,
        "Neutron_Number": 96
    },
    {
        "Element_Name": "Holmium",
        "Element_Symbol": "Ho",
        "Atomic_Number": 67,
        "Atomic_Mass": 164.93,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 67,
        "Electron_Number": 67,
        "Neutron_Number": 98
    },
    {
        "Element_Name": "Erbium",
        "Element_Symbol": "Er",
        "Atomic_Number": 68,
        "Atomic_Mass": 167.26,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 68,
        "Electron_Number": 68,
        "Neutron_Number": 99
    },
    {
        "Element_Name": "Thulium",
        "Element_Symbol": "Tm",
        "Atomic_Number": 69,
        "Atomic_Mass": 168.93,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 3,
        "Proton_Number": 69,
        "Electron_Number": 69,
        "Neutron_Number": 100
    },
    {
        "Element_Name": "Ytterbium",
        "Element_Symbol": "Yb",
        "Atomic_Number": 70,
        "Atomic_Mass": 173.05,
        "Element_Group": None,
        "Element_Group_Type": "Lanthanide",
        "Element_Valence": 2,
        "Proton_Number": 70,
        "Electron_Number": 70,
        "Neutron_Number": 103
    },
    {
        "Element_Name": "Lutetium",
        "Element_Symbol": "Lu",
        "Atomic_Number": 71,
        "Atomic_Mass": 174.97,
        "Element_Group": 3,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 71,
        "Electron_Number": 71,
        "Neutron_Number": 104
    },
    {
        "Element_Name": "Hafnium",
        "Element_Symbol": "Hf",
        "Atomic_Number": 72,
        "Atomic_Mass": 178.49,
        "Element_Group": 4,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 72,
        "Electron_Number": 72,
        "Neutron_Number": 106
    },
    {
        "Element_Name": "Tantalum",
        "Element_Symbol": "Ta",
        "Atomic_Number": 73,
        "Atomic_Mass": 180.95,
        "Element_Group": 5,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 5,
        "Proton_Number": 73,
        "Electron_Number": 73,
        "Neutron_Number": 108
    },
    {
        "Element_Name": "Tungsten",
        "Element_Symbol": "W",
        "Atomic_Number": 74,
        "Atomic_Mass": 183.84,
        "Element_Group": 6,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 6,
        "Proton_Number": 74,
        "Electron_Number": 74,
        "Neutron_Number": 110
    },
    {
        "Element_Name": "Rhenium",
        "Element_Symbol": "Re",
        "Atomic_Number": 75,
        "Atomic_Mass": 186.21,
        "Element_Group": 7,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 7,
        "Proton_Number": 75,
        "Electron_Number": 75,
        "Neutron_Number": 111
    },
    {
        "Element_Name": "Osmium",
        "Element_Symbol": "Os",
        "Atomic_Number": 76,
        "Atomic_Mass": 190.23,
        "Element_Group": 8,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 76,
        "Electron_Number": 76,
        "Neutron_Number": 114
    },
    {
        "Element_Name": "Iridium",
        "Element_Symbol": "Ir",
        "Atomic_Number": 77,
        "Atomic_Mass": 192.22,
        "Element_Group": 9,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 77,
        "Electron_Number": 77,
        "Neutron_Number": 115
    },
    {
        "Element_Name": "Platinum",
        "Element_Symbol": "Pt",
        "Atomic_Number": 78,
        "Atomic_Mass": 195.08,
        "Element_Group": 10,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 78,
        "Electron_Number": 78,
        "Neutron_Number": 117
    },
    {
        "Element_Name": "Gold",
        "Element_Symbol": "Au",
        "Atomic_Number": 79,
        "Atomic_Mass": 196.97,
        "Element_Group": 11,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 1,
        "Proton_Number": 79,
        "Electron_Number": 79,
        "Neutron_Number": 118
    },
    {
        "Element_Name": "Mercury",
        "Element_Symbol": "Hg",
        "Atomic_Number": 80,
        "Atomic_Mass": 200.59,
        "Element_Group": 12,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": 2,
        "Proton_Number": 80,
        "Electron_Number": 80,
        "Neutron_Number": 121
    },
    {
        "Element_Name": "Thallium",
        "Element_Symbol": "Tl",
        "Atomic_Number": 81,
        "Atomic_Mass": 204.38,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 3,
        "Proton_Number": 81,
        "Electron_Number": 81,
        "Neutron_Number": 123
    },
    {
        "Element_Name": "Lead",
        "Element_Symbol": "Pb",
        "Atomic_Number": 82,
        "Atomic_Mass": 207.2,
        "Element_Group": 14,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 4,
        "Proton_Number": 82,
        "Electron_Number": 82,
        "Neutron_Number": 125
    },
    {
        "Element_Name": "Bismuth",
        "Element_Symbol": "Bi",
        "Atomic_Number": 83,
        "Atomic_Mass": 208.98,
        "Element_Group": 15,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": 5,
        "Proton_Number": 83,
        "Electron_Number": 83,
        "Neutron_Number": 126
    },
    {
        "Element_Name": "Polonium",
        "Element_Symbol": "Po",
        "Atomic_Number": 84,
        "Atomic_Mass": 209,
        "Element_Group": 16,
        "Element_Group_Type": "Metalloid",
        "Element_Valence": 6,
        "Proton_Number": 84,
        "Electron_Number": 84,
        "Neutron_Number": 125
    },
    {
        "Element_Name": "Astatine",
        "Element_Symbol": "At",
        "Atomic_Number": 85,
        "Atomic_Mass": 210,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": 7,
        "Proton_Number": 85,
        "Electron_Number": 85,
        "Neutron_Number": 125
    },
    {
        "Element_Name": "Radon",
        "Element_Symbol": "Rn",
        "Atomic_Number": 86,
        "Atomic_Mass": 222,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": 0,
        "Proton_Number": 86,
        "Electron_Number": 86,
        "Neutron_Number": 136
    },
    {
        "Element_Name": "Francium",
        "Element_Symbol": "Fr",
        "Atomic_Number": 87,
        "Atomic_Mass": 223,
        "Element_Group": 1,
        "Element_Group_Type": "Alkali Metal",
        "Element_Valence": 1,
        "Proton_Number": 87,
        "Electron_Number": 87,
        "Neutron_Number": 136
    },
    {
        "Element_Name": "Radium",
        "Element_Symbol": "Ra",
        "Atomic_Number": 88,
        "Atomic_Mass": 226,
        "Element_Group": 2,
        "Element_Group_Type": "Alkaline Earth Metal",
        "Element_Valence": 2,
        "Proton_Number": 88,
        "Electron_Number": 88,
        "Neutron_Number": 138
    },
    {
        "Element_Name": "Actinium",
        "Element_Symbol": "Ac",
        "Atomic_Number": 89,
        "Atomic_Mass": 227,
        "Element_Group": 3,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 89,
        "Electron_Number": 89,
        "Neutron_Number": 138
    },
    {
        "Element_Name": "Thorium",
        "Element_Symbol": "Th",
        "Atomic_Number": 90,
        "Atomic_Mass": 232.04,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 4,
        "Proton_Number": 90,
        "Electron_Number": 90,
        "Neutron_Number": 142
    },
    {
        "Element_Name": "Protactinium",
        "Element_Symbol": "Pa",
        "Atomic_Number": 91,
        "Atomic_Mass": 231.04,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 5,
        "Proton_Number": 91,
        "Electron_Number": 91,
        "Neutron_Number": 140
    },
    {
        "Element_Name": "Uranium",
        "Element_Symbol": "U",
        "Atomic_Number": 92,
        "Atomic_Mass": 238.03,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 6,
        "Proton_Number": 92,
        "Electron_Number": 92,
        "Neutron_Number": 146
    },
    {
        "Element_Name": "Neptunium",
        "Element_Symbol": "Np",
        "Atomic_Number": 93,
        "Atomic_Mass": 237,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 7,
        "Proton_Number": 93,
        "Electron_Number": 93,
        "Neutron_Number": 144
    },
    {
        "Element_Name": "Plutonium",
        "Element_Symbol": "Pu",
        "Atomic_Number": 94,
        "Atomic_Mass": 244,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 6,
        "Proton_Number": 94,
        "Electron_Number": 94,
        "Neutron_Number": 150
    },
    {
        "Element_Name": "Americium",
        "Element_Symbol": "Am",
        "Atomic_Number": 95,
        "Atomic_Mass": 243,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 95,
        "Electron_Number": 95,
        "Neutron_Number": 148
    },
    {
        "Element_Name": "Curium",
        "Element_Symbol": "Cm",
        "Atomic_Number": 96,
        "Atomic_Mass": 247,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 96,
        "Electron_Number": 96,
        "Neutron_Number": 151
    },
    {
        "Element_Name": "Berkelium",
        "Element_Symbol": "Bk",
        "Atomic_Number": 97,
        "Atomic_Mass": 247,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 97,
        "Electron_Number": 97,
        "Neutron_Number": 150
    },
    {
        "Element_Name": "Californium",
        "Element_Symbol": "Cf",
        "Atomic_Number": 98,
        "Atomic_Mass": 251,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 98,
        "Electron_Number": 98,
        "Neutron_Number": 153
    },
    {
        "Element_Name": "Einsteinium",
        "Element_Symbol": "Es",
        "Atomic_Number": 99,
        "Atomic_Mass": 252,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 99,
        "Electron_Number": 99,
        "Neutron_Number": 153
    },
    {
        "Element_Name": "Fermium",
        "Element_Symbol": "Fm",
        "Atomic_Number": 100,
        "Atomic_Mass": 257,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 100,
        "Electron_Number": 100,
        "Neutron_Number": 157
    },
    {
        "Element_Name": "Mendelevium",
        "Element_Symbol": "Md",
        "Atomic_Number": 101,
        "Atomic_Mass": 258,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 101,
        "Electron_Number": 101,
        "Neutron_Number": 157
    },
    {
        "Element_Name": "Nobelium",
        "Element_Symbol": "No",
        "Atomic_Number": 102,
        "Atomic_Mass": 259,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 2,
        "Proton_Number": 102,
        "Electron_Number": 102,
        "Neutron_Number": 157
    },
        {
        "Element_Name": "Lawrencium",
        "Element_Symbol": "Lr",
        "Atomic_Number": 103,
        "Atomic_Mass": 266,
        "Element_Group": None,
        "Element_Group_Type": "Actinide",
        "Element_Valence": 3,
        "Proton_Number": 103,
        "Electron_Number": 103,
        "Neutron_Number": 163
    },
    {
        "Element_Name": "Rutherfordium",
        "Element_Symbol": "Rf",
        "Atomic_Number": 104,
        "Atomic_Mass": 267,
        "Element_Group": 4,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 104,
        "Electron_Number": 104,
        "Neutron_Number": 163
    },
    {
        "Element_Name": "Dubnium",
        "Element_Symbol": "Db",
        "Atomic_Number": 105,
        "Atomic_Mass": 268,
        "Element_Group": 5,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 105,
        "Electron_Number": 105,
        "Neutron_Number": 163
    },
    {
        "Element_Name": "Seaborgium",
        "Element_Symbol": "Sg",
        "Atomic_Number": 106,
        "Atomic_Mass": 269,
        "Element_Group": 6,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 106,
        "Electron_Number": 106,
        "Neutron_Number": 163
    },
    {
        "Element_Name": "Bohrium",
        "Element_Symbol": "Bh",
        "Atomic_Number": 107,
        "Atomic_Mass": 270,
        "Element_Group": 7,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 107,
        "Electron_Number": 107,
        "Neutron_Number": 163
    },
    {
        "Element_Name": "Hassium",
        "Element_Symbol": "Hs",
        "Atomic_Number": 108,
        "Atomic_Mass": 269,
        "Element_Group": 8,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 108,
        "Electron_Number": 108,
        "Neutron_Number": 161
    },
    {
        "Element_Name": "Meitnerium",
        "Element_Symbol": "Mt",
        "Atomic_Number": 109,
        "Atomic_Mass": 278,
        "Element_Group": 9,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 109,
        "Electron_Number": 109,
        "Neutron_Number": 169
    },
    {
        "Element_Name": "Darmstadtium",
        "Element_Symbol": "Ds",
        "Atomic_Number": 110,
        "Atomic_Mass": 281,
        "Element_Group": 10,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 110,
        "Electron_Number": 110,
        "Neutron_Number": 171
    },
    {
        "Element_Name": "Roentgenium",
        "Element_Symbol": "Rg",
        "Atomic_Number": 111,
        "Atomic_Mass": 282,
        "Element_Group": 11,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 111,
        "Electron_Number": 111,
        "Neutron_Number": 171
    },
    {
        "Element_Name": "Copernicium",
        "Element_Symbol": "Cn",
        "Atomic_Number": 112,
        "Atomic_Mass": 285,
        "Element_Group": 12,
        "Element_Group_Type": "Transition Metal",
        "Element_Valence": None,
        "Proton_Number": 112,
        "Electron_Number": 112,
        "Neutron_Number": 173
    },
    {
        "Element_Name": "Nihonium",
        "Element_Symbol": "Nh",
        "Atomic_Number": 113,
        "Atomic_Mass": 286,
        "Element_Group": 13,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": None,
        "Proton_Number": 113,
        "Electron_Number": 113,
        "Neutron_Number": 173
    },
    {
        "Element_Name": "Flerovium",
        "Element_Symbol": "Fl",
        "Atomic_Number": 114,
        "Atomic_Mass": 289,
        "Element_Group": 14,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": None,
        "Proton_Number": 114,
        "Electron_Number": 114,
        "Neutron_Number": 175
    },
    {
        "Element_Name": "Moscovium",
        "Element_Symbol": "Mc",
        "Atomic_Number": 115,
        "Atomic_Mass": 290,
        "Element_Group": 15,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": None,
        "Proton_Number": 115,
        "Electron_Number": 115,
        "Neutron_Number": 175
    },
    {
        "Element_Name": "Livermorium",
        "Element_Symbol": "Lv",
        "Atomic_Number": 116,
        "Atomic_Mass": 293,
        "Element_Group": 16,
        "Element_Group_Type": "Post-transition Metal",
        "Element_Valence": None,
        "Proton_Number": 116,
        "Electron_Number": 116,
        "Neutron_Number": 177
    },
    {
        "Element_Name": "Tennessine",
        "Element_Symbol": "Ts",
        "Atomic_Number": 117,
        "Atomic_Mass": 294,
        "Element_Group": 17,
        "Element_Group_Type": "Halogen",
        "Element_Valence": None,
        "Proton_Number": 117,
        "Electron_Number": 117,
        "Neutron_Number": 177
    },
    {
        "Element_Name": "Oganesson",
        "Element_Symbol": "Og",
        "Atomic_Number": 118,
        "Atomic_Mass": 294,
        "Element_Group": 18,
        "Element_Group_Type": "Noble Gas",
        "Element_Valence": None,
        "Proton_Number": 118,
        "Electron_Number": 118,
        "Neutron_Number": 176
    }
]
print("Periodic Table of Elements Study APP")
User_Input = ""
User_Choice = input("Would you like to 'Quiz' or 'Study'? ")

def Quiz():
    print("Quiz Mode: Guess the Element Name by Symbol!")
    Correct_Score = 0
    Incorrect_Score= 0

    while True:
        element = random.choice(Elements)
        symbol = element["Element_Symbol"]
        correct_name = element["Element_Name"]

        user_answer = input(f" What is the name of the element with symbol '{symbol}'? (or type 'Exit' to quit): ")

        if user_answer.lower() == "exit":
            print(f" You finished the quiz! Score: {score}/{total}")
            break
        if user_answer == correct_name:
            print("Correct!")
            Correct_Score += 1
            print("Correct Score =", Correct_Score)
            print("InCorrect Score =", Incorrect_Score)
        else:
            print(f"Incorrect. The correct answer was '{correct_name}")
            Incorrect_Score += 1
            print("Correct Score =", Correct_Score)
            print("InCorrect Score =", Incorrect_Score)
if User_Choice == "Study":
    while User_Input != "Exit":
        User_Input = input("Input an Element Name to Learn --> Enter 'Exit' to Quit: ")
        found = False
        for element in Elements:
            if element["Element_Name"].lower() == User_Input.lower():
                found = True
                print("******************")
                print(f"Element Name: {element['Element_Name']}")
                print(f"Symbol: {element['Element_Symbol']}")
                print(f"Atomic Number: {element['Atomic_Number']}")
                print(f"Protons: {element['Proton_Number']}")
                print(f"Electrons: {element['Electron_Number']}")
                print(f"Neutrons: {element['Neutron_Number']}")
                print(f"Atomic Mass: {element['Atomic_Mass']}")
                print(f"Group: {element['Element_Group']}")
                print(f"Group: {element['Element_Group_Type']}")
                print(f"Valence Electrons: {element['Element_Valence']}")
        if not found and User_Input != "Exit":
            print("Element not found.")
elif User_Choice == "Quiz":
    Quiz()
else:
    print("Invalid choice. Please enter 'Quiz' or 'Study'.")
